# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpeek < Formula
  desc "Interactive terminal data viewer for CSV, TSV, JSON, and JSONL files"
  homepage "https://github.com/GonzaloFuentes28/dpeek"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GonzaloFuentes28/dpeek/releases/download/v0.2.0/dpeek_darwin_amd64.tar.gz"
      sha256 "332a326b9b08af93e19b12c5231623b831cd4df4d34ceeff182de2e31c273817"

      define_method(:install) do
        bin.install "dpeek"
        man1.install "dpeek.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GonzaloFuentes28/dpeek/releases/download/v0.2.0/dpeek_darwin_arm64.tar.gz"
      sha256 "321ee3587d4bf619f41abf3d62317c2b4bbd9d903b4708d98ed3cce0788436df"

      define_method(:install) do
        bin.install "dpeek"
        man1.install "dpeek.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GonzaloFuentes28/dpeek/releases/download/v0.2.0/dpeek_linux_amd64.tar.gz"
      sha256 "d51ce12b1e15a730ad717b4b169f2c62853e0d138efb194c536116d8873de2de"
      define_method(:install) do
        bin.install "dpeek"
        man1.install "dpeek.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GonzaloFuentes28/dpeek/releases/download/v0.2.0/dpeek_linux_arm64.tar.gz"
      sha256 "f9c8e667d23ee85a6f9bf1dee20a5632975eea81cde58444bb2b67f03602bfcf"
      define_method(:install) do
        bin.install "dpeek"
        man1.install "dpeek.1"
      end
    end
  end

  test do
    assert_match "dpeek", shell_output("#{bin}/dpeek --version")
  end
end
